CC = gcc
WINDRES = windres
RES =
OBJ = main.o world.o 3dEngine\rotate.o 3dEngine\rotate2.o 3dEngine\applyRotLocSz.o 3dEngine\transform.o 3dEngine\drawMeshGL.o $(RES)
LIBS = -mwindows -lopengl32
BIN = loader.exe
CFLAGS = -Wall
RM = del

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(OBJ) -o $(BIN) $(LIBS)
